### PR TITLE
Support of JACO 7 DoF arms

### PR DESCRIPTION
**Pull request by sparadiskinova**

### CODE REVIEW

**Comment by brandonjdehart** [comment]
I'm excited to see that this has been pulled into the main branch now! Does this mean that I can follow the standard protocol for updating the movo to the latest master branch and will be able to run our unit with the 7-DOF arms?

**Comment by martine1406** [comment]
Hi Brandon. We will conduct a few last tests on Monday, but yeah you should be good to go!

**Comment by brandonjdehart** [comment]
Let me know once you've completed your tests, as I would like to try to get this up and running this week on our Movo.

Have you made any progress on writing up a formal step-by-step procedure for adding 7-DOF arms to a Movo? There is the potential that in future I will be switching arms fairly often, depending on our which avenues the researchers decide to pursue.

**Comment by martine1406** [comment]
Hi @brandonjdehart 

we do not have a formal procedure yet other than the instructions you can find in the html documentation you received with movo (the "Movo user guide")- you have a section Kinova arms installation. The procedure to mount and unmount a 7 dof arm is identical as for a 6 dof. Please let us know if you experience any problem following this procedure and we will try to update it accordingly to make it clearer. 

Thanks

**Comment by brandonjdehart** [comment]
I used the guide to install and uninstall the arms on the mechanical/electrical side of things, but I'm more wondering if there is a process as far as the software and movo1/movo2 computers that I need to follow to be able to easily switch between 0, 1, and 2 arms, 6- or 7-DOF arms, different grippers, etc.

**Comment by sparadiskinova** [comment]
Hi Brandon,

When you pull the latest of the master the point 1 and 2 of https://github.com/orgs/Kinovarobotics/teams/movo-beta-program/discussions/22?from_comment=1#discussion-22-comment-1 must be executed.

The configuration of the MOVO code base is determined by this file:

~/movo_ws/src/src/movo_common/movo_config/movo_config.bash

These parameters can be adjusted accordingly with your current MOVO assembly.

This configuration file must be identical on all 3 PC (MOVO1, MOVO2 and development PC) and a catkin_make clean and catkin_make must also be done when it is modified

#Kinova arm configurations (the right arm should be the default if there is only one)
export MOVO_HAS_KINOVA_ARM=true
export MOVO_HAS_TWO_KINOVA_ARMS=true
...
export MOVO_HAS_KINOVA_ARM_7DOF=true
export MOVO_HAS_KINOVA_ARM_6DOF=false

#gripper configurations

#Kinova KG2
export USE_KG2_FOR_MOVEIT_CONFIG=false
export MOVO_HAS_RIGHT_KG2_GRIPPER=false
export MOVO_HAS_LEFT_KG2_GRIPPER=false

#Kinova KG3
export USE_KG3_FOR_MOVEIT_CONFIG=true
export MOVO_HAS_RIGHT_KG3_GRIPPER=true
export MOVO_HAS_LEFT_KG3_GRIPPER=true

#Robotiq 85 two finger gripper
export USE_R85_FOR_MOVEIT_CONFIG=false
export MOVO_HAS_RIGHT_ROBOTIQ_GRIPPER=false
export MOVO_HAS_LEFT_ROBOTIQ_GRIPPER=false

Within a couple of days, all parameters of that configuration file will be documented.

Sebastien

**Comment by brandonjdehart** [comment]
Has there been any progress on documenting the parameters in the configuration file? It seems like this file is of critical importance to the rest of the code working properly, based on the issues that came up while a few of us were upgrading to version 1.1.0 of the software.

**Comment by martine1406** [comment]
Hi @brandonjdehart 

Are any of these parameters unclear for you? If you have any question on their meaning or their effect on the robot, let me know and we can add more details in the configuration file. The main configurations you should be interested in are the number of arms, type of arms, number of gripper and type of grippers . These are the configurations that will vary from one movo to the other.

The default configuration is for a movo with two 7 dof arms and two KG3 grippers. 

for the number of arms:
no arm means MOVO_HAS_KINOVA_ARM = false and MOVO_HAS_TWO_KINOVA_ARMS=false
one arm (considered as the right arm) means MOVO_HAS_KINOVA_ARM = true and MOVO_HAS_TWO_KINOVA_ARMS=false
two arms means MOVO_HAS_KINOVA_ARM = true and MOVO_HAS_TWO_KINOVA_ARMS=true

for the type of arms
6 dof arms means MOVO_HAS_KINOVA_ARM_7DOF = false and MOVO_HAS_KINOVA_ARM_6DOF=true
7 dof arms means MOVO_HAS_KINOVA_ARM_7DOF = true and MOVO_HAS_KINOVA_ARM_6DOF=false

for the number of grippers
no gripper means MOVO_HAS_RIGHT_(*)_GRIPPER = false and MOVO_HAS_LEFT_(*)_GRIPPER = false
one gripper (considered the right) means  MOVO_HAS_RIGHT_(*)_GRIPPER = true and MOVO_HAS_LEFT_(*)_GRIPPER = false
two grippers means  MOVO_HAS_RIGHT_(*)_GRIPPER = true and MOVO_HAS_LEFT_(*)_GRIPPER = true

for the type of grippers
kg3 grippers means MOVO_HAS_RIGHT_KG3_GRIPPER = true and MOVO_HAS_LEFT_KG3_GRIPPER = true, but MOVO_HAS_RIGHT_KG2_GRIPPER=false, MOVO_HAS_LEFT_KG2_GRIPPER = false, MOVO_HAS_RIGHT_ROBOTIQ_GRIPPER = false and MOVO_HAS_LEFT_ROBOTIQ_GRIPPER = false. 

kg2 grippers means MOVO_HAS_RIGHT_KG2_GRIPPER = true and MOVO_HAS_LEFT_KG2_GRIPPER = true, but MOVO_HAS_RIGHT_KG3_GRIPPER=false, MOVO_HAS_LEFT_KG3_GRIPPER = false, MOVO_HAS_RIGHT_ROBOTIQ_GRIPPER = false and MOVO_HAS_LEFT_ROBOTIQ_GRIPPER = false. 

Robotiq grippers means MOVO_HAS_RIGHT_ROBOTIQ_GRIPPER = true and MOVO_HAS_LEFT_ROBOTIQ_GRIPPER = true, but MOVO_HAS_RIGHT_KG3_GRIPPER=false, MOVO_HAS_LEFT_KG3_GRIPPER = false, MOVO_HAS_RIGHT_KG2_GRIPPER = false and MOVO_HAS_LEFT_KG2_GRIPPER = false. 

Let me know if anything is unclear
Thanks
Martine

**Comment by brandonjdehart** [comment]
The arm and gripper definitions are all fairly verbose, so those I'm less concerned about (although knowing which ones mean the code will ignore others would be useful). The main reason I asked about the documentation was that @sparadiskinova said the file would be documented "within a couple of days" a month ago. Obviously not a time-sensitive thing, just wondering when it would be happening.

As an example of why I think the documentation would be helpful is that the assumption that a single-arm Movo only has a right arm is unclear from the variable names. Instead, couldn't HAS_KINOVA_ARM and HAS_KINOVA_ARMS be replaced with HAS_KINOVA_RIGHT_ARM and HAS_KINOVA_LEFT_ARM to avoid the assumption about where a single arm is connected (similar to the grippers)?

It seems like this code as-written wouldn't allow a 6-DOF arm and a 7-DOF arm to be connected to the same Movo, is that correct? Could we (again, like the grippers) change to variables like HAS_KINOVA_RIGHT_ARM_7D0F, HAS_KINOVA_LEFT_ARM_6DOF, etc. to be more specific about the DOFs for each arm?

**Comment by martine1406** [comment]
Hi @brandonjdehart 

Your assumption is correct. We wouldn't wouldn't allow a 6-DOF arm and a 7-DOF arm to be connected to the same Movo the way it is implemented. I also agree that some variable names could have been chosen differently. Changing these configuration variable however requires several changes in many launch files. Especially the HAS_KINOVA_RIGHT_ARM_7D0F, HAS_KINOVA_LEFT_ARM_6DOF thing may require us to rethink some of the code structure. Still, it is something to keep in mind for future improvement I think

Thanks for the clarification and for your ideas
Martine

**Pull request merged**
